### ISSUE TITLE
ProDy returns wrong sequence for PDB entry 3J9M chain AW

### ISSUE THREAD

**Issue by jonathanking** [prody/ProDy#1038] opened 2020-05-13 19:56 UTC
The returned sequence is not correct in this example.

```
p = pr.parseCIF("3j9m", chain="AW")
p.ca.getSequence()
Out[5]: 'SSKNLGGKSSGRRQGIKKMEGHYVHAGNIIATQRHFRWHPGAHVGVGKNKCLYALEEGIVRYTKEVYVPHPRNTEAVDLITRLPKGAVLYKTFVHVVPAKPEGTFKLVAMLVESFASMLRHSPLTQMGPAKDKLVIGRIFHIVENDLYIDFGGKFHCVCRRPEVDGEKYQKGTRVRLRLLDLELTSRFLGATTDTTVLEANAVLLGIQ'
```

According to the [online PDB entry](https://www.rcsb.org/fasta/entry/3J9M/display), the complete sequence for chain AW is:
```
"MAALCRTRAVAAESHFLRVFLFFRPFRGVGTESGSESGSSNAKEPKTRAGGFASALERHSELLQKVEPLQKGSPKNVESFASMLRHSPLTQMGPAKDKLVIGRIFHIVENDLYIDFGGKFHCVCRRPEVDGEKYQKGTRVRLRLLDLELTSRFLGATTDTTVLEANAVLLGIQESKDSRSKEEHHEK".
```

The returned sequence (top), when aligned to the correct sequence (bottom), exhitibs a really poor alignment (since we expect ProDy's sequence to be a strict subsequence of the full sequence) and is suggesting to me that ProDy is returning the wrong sequence:
```
SSKNLGGKSSGRRQGIKKMEGHYVHAGNIIA---TQR------HF-RWHPGAHV--------GVG-KNKCLYALE---E-G----IVRYTKEVYVPHP--R------NTEAVDL-ITR---LPKGAVL-YKTFVHVV-P--AK--PEGTFK-LVAMLVESFASMLRHSPLTQMGPAKDKLVIGRIFHIVENDLYIDFGGKFHCVCRRPEVDGEKYQKGTRVRLRLLDLELTSRFLGATTDTTVLEANAVLLGIQ--------------
------------------|------|----|---|-|------||-|------|--------|||---------|---|-|---------||-----|--|---------|--|---|---|-----|--|-----|-|---|--|----|------|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||--------------
------------------M------A----ALCRT-RAVAAESHFLR------VFLFFRPFRGVGT--------ESGSESGSSNA-----KE-----PKTRAGGFAS---A--LE--RHSEL-----LQ-K-----VEPLQ-KGSP----KN-----VESFASMLRHSPLTQMGPAKDKLVIGRIFHIVENDLYIDFGGKFHCVCRRPEVDGEKYQKGTRVRLRLLDLELTSRFLGATTDTTVLEANAVLLGIQESKDSRSKEEHHEK

```

I was looking around a bit and I noticed that the full sequence for chain W  is relatively similar to Prody's returned sequence for chain AW. Maybe Prody is using information from chain W instead of AW?

Chain W's full sequence is:
```
"SSKNLGGKSSGRRQGIKKMEGHYVHAGNIIATQRHFRWHPGAHVGVGKNKCLYALEEGIVRYTKEVYVPHPRNTEAVDLITRLPKGAVLYKTFVHVVPAKPEGTFKLVAML"
```

I am using ProDy v1.10.11.

**Comment by SHZ66** [comment] 2020-05-13 20:50
I think just recently we fixed the problem with two-letter chain IDs. Maybe you can try out the latest dev version and see if the problem persists. @jamesmkrieger, do you have something to add on this?

**Comment by jonathanking** [comment] 2020-05-13 21:59
It says that the issue you mentioned was merged into Master, and I think I am using the latest version even though I used pip to update the package. Unless using pip to update to 1.10.11 is problematic?

**Comment by SHZ66** [comment] 2020-05-13 22:18
Yes, it was merged but not released to pip yet. You can try to install from source by downloading the zip from this repo, unzip it, enter the folder, and type:

```
pip setup.py install
```

and see if this dev version fixes your problem or not. You may need to pip uninstall ProDy first just to avoid confusion.

**Comment by jonathanking** [comment] 2020-05-14 15:24
Thanks for the suggestion. I cloned ProDy, and ran `python setup.py build_ext --inplace --force` followed by `python setup.py install`. The issue still seems to be present (returned sequence is not a subsequence of the true sequence).

```
Python 3.7.4 (default, Aug 13 2019, 15:17:50)
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import prody as pr
>>> pr.__version__
'1.11'
>>> p = pr.parseCIF("3j9m", chain="AW")
>>> p.ca.getSequence()
'SSKNLGGKSSGRRQGIKKMEGHYVHAGNIIATQRHFRWHPGAHVGVGKNKCLYALEEGIVRYTKEVYVPHPRNTEAVDLITRLPKGAVLYKTFVHVVPAKPEGTFKLVAMLVESFASMLRHSPLTQMGPAKDKLVIGRIFHIVENDLYIDFGGKFHCVCRRPEVDGEKYQKGTRVRLRLLDLELTSRFLGATTDTTVLEANAVLLGIQ'
>>> pr.__file__
'/Users/jonathanking/anaconda3/envs/transformer/lib/python3.7/site-packages/ProDy-1.11-py3.7-macosx-10.9-x86_64.egg/prody/__init__.py'
```

**Comment by jamesmkrieger** [comment] 2020-05-14 20:44
Ok, I'll have a look.

**Comment by jamesmkrieger** [comment] 2020-05-14 21:36
Can you see if this fix helps please?

**Comment by jamesmkrieger** [comment] 2020-05-14 21:38
oh actually isn't it

**Comment by jamesmkrieger** [comment] 2020-05-14 21:41
I think the problem is actually that we use "in" for the checking. We don't have a way of handling parsing multi-character chain IDs for that.

**Comment by jamesmkrieger** [comment] 2020-05-14 22:00
Ok I fixed it now!

**Comment by jonathanking** [comment] 2020-05-15 02:08
It works as far as I can tell too! Thanks, @jamesmkrieger ! :smiley:

**Comment by SHZ66** [comment] 2020-05-15 02:10
Great! I am merging it too

**Comment by jamesmkrieger** [comment] 2020-05-15 10:28
Great! Let's close the issue then

**Comment by jamesmkrieger** [comment] 2020-05-15 10:28
Oh also you're welcome

**Closed by jamesmkrieger** 2020-05-15 10:28 UTC
