### ISSUE TITLE
ProDy no longer builds on OS X with clang

### ISSUE THREAD

**Issue by cowsandmilk** [prody/ProDy#666] opened 2018-05-11 18:31 UTC
ProDy 1.10.2 doesn't compile with clang on OS X (and 1.10.1 and 1.10.0)

From OS X 10.13.4 , latest Xcode clang

> clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Iprody/utilities/tnt -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c prody/proteins/ccealign/ccealignmodule.cpp -o build/temp.macosx-10.13-x86_64-3.6/prody/proteins/ccealign/ccealignmodule.o
In file included from prody/proteins/ccealign/ccealignmodule.cpp:38:
In file included from prody/proteins/ccealign/ccealignmodule.h:42:
In file included from prody/utilities/tnt/tnt.h:41:
prody/utilities/tnt/tnt_array1d.h:238:15: warning: '&&' within '||' [-Wlogical-op-parentheses]
        if ((i0 > 0) && (i1 < n_) || (i0 <= i1))
            ~~~~~~~~~^~~~~~~~~~~~ ~~
prody/utilities/tnt/tnt_array1d.h:238:15: note: place parentheses around the '&&' expression to silence this warning
        if ((i0 > 0) && (i1 < n_) || (i0 <= i1))
                     ^
            (                    )
In file included from prody/proteins/ccealign/ccealignmodule.cpp:38:
In file included from prody/proteins/ccealign/ccealignmodule.h:42:
In file included from prody/utilities/tnt/tnt.h:48:
prody/utilities/tnt/tnt_fortran_array1d.h:224:15: warning: '&&' within '||' [-Wlogical-op-parentheses]
        if ((i0 > 0) && (i1 < n_) || (i0 <= i1))
            ~~~~~~~~~^~~~~~~~~~~~ ~~
prody/utilities/tnt/tnt_fortran_array1d.h:224:15: note: place parentheses around the '&&' expression to silence this warning
        if ((i0 > 0) && (i1 < n_) || (i0 <= i1))
                     ^
            (                    )
In file included from prody/proteins/ccealign/ccealignmodule.cpp:38:
In file included from prody/proteins/ccealign/ccealignmodule.h:42:
In file included from prody/utilities/tnt/tnt.h:55:
prody/utilities/tnt/tnt_sparse_matrix_csr.h:97:3: error: no matching constructor for initialization of 'Array1D<int>'
                rowptr_(M, r), colind_(nz, c), dim1_(M), dim2_(N) {}
                ^       ~~~~
prody/utilities/tnt/tnt_array1d.h:63:11: note: candidate constructor not viable: no known conversion from 'const int *' to 'const int' for 2nd argument; dereference the argument with *
                 Array1D(int n, const T &a);
                 ^
prody/utilities/tnt/tnt_array1d.h:64:11: note: candidate constructor not viable: 2nd argument ('const int *') would lose const qualifier
                 Array1D(int n,  T *a);
                 ^
prody/utilities/tnt/tnt_array1d.h:62:11: note: candidate constructor not viable: requires single argument 'n', but 2 arguments were provided
        explicit Array1D(int n);
                 ^
prody/utilities/tnt/tnt_array1d.h:65:14: note: candidate constructor not viable: requires single argument 'A', but 2 arguments were provided
    inline   Array1D(const Array1D &A);
             ^
prody/utilities/tnt/tnt_array1d.h:61:11: note: candidate constructor not viable: requires 0 arguments, but 2 were provided
                 Array1D();
                 ^
In file included from prody/proteins/ccealign/ccealignmodule.cpp:38:
In file included from prody/proteins/ccealign/ccealignmodule.h:42:
In file included from prody/utilities/tnt/tnt.h:55:
prody/utilities/tnt/tnt_sparse_matrix_csr.h:97:18: error: no matching constructor for initialization of 'Array1D<int>'
                rowptr_(M, r), colind_(nz, c), dim1_(M), dim2_(N) {}
                               ^       ~~~~~
prody/utilities/tnt/tnt_array1d.h:63:11: note: candidate constructor not viable: no known conversion from 'const int *' to 'const int' for 2nd argument; dereference the argument with *
                 Array1D(int n, const T &a);
                 ^
prody/utilities/tnt/tnt_array1d.h:64:11: note: candidate constructor not viable: 2nd argument ('const int *') would lose const qualifier
                 Array1D(int n,  T *a);
                 ^
prody/utilities/tnt/tnt_array1d.h:62:11: note: candidate constructor not viable: requires single argument 'n', but 2 arguments were provided
        explicit Array1D(int n);
                 ^
prody/utilities/tnt/tnt_array1d.h:65:14: note: candidate constructor not viable: requires single argument 'A', but 2 arguments were provided
    inline   Array1D(const Array1D &A);
             ^
prody/utilities/tnt/tnt_array1d.h:61:11: note: candidate constructor not viable: requires 0 arguments, but 2 were provided
                 Array1D();
                 ^
2 warnings and 2 errors generated.
error: command 'clang' failed with exit status 1

**Comment by SHZ66** [comment] 2018-05-11 19:35
Thank you for reporting. We are aware of this issue and it is caused by the tnt library redistributed with ProDy. We will figure out a workaround.

**Comment by SHZ66** [comment] 2018-05-14 18:07
This is fixed and will be available in the next release. In the meantime, please check out #669.

**Comment by SHZ66** [comment] 2018-05-15 04:49
The new release is [out](https://pypi.org/project/ProDy/#description), so I will close this issue for now.

**Closed by SHZ66** 2018-05-15 04:49 UTC
Labels: Defect
