### ISSUE TITLE
ProDy-1.7.win-amd64-py2.7.exe Download

### ISSUE THREAD

**Issue by reedharrison** [prody/ProDy#281] opened 2016-03-29 00:19 UTC
Hello,

I am trying to install ProDy to be compatible with 64 bit Python 2.7 in Windows; however, this download seems to contain a virus according to Windows Defender. Is there any way you can check this file and see if my antivirus is misclassifying this executable?

On a side note, I have also tried compiling the source (python setup.py install) but this does not seem to work. I think this may be expected since the INSTALL.rst file says:

" *Windows*: You need to use **32-bit** Python on Windows to be able to
  install NumPy and ProDy."

Thanks for any help/advice you can provide.

Best,

Reed Harrison

**Comment by reedharrison** [comment] 2016-04-01 20:19
Quick follow up: I am able to install ProDy in 64 bit Python 2.7 now (several different ways to install result in the same issue); however, selections within PDB files seem to be broken. Perhaps this is because ProDy is not compatible with 64 bit numpy? I have put the error and associated commands below.

Commands:
import prody as pd
pdb = pd.parsePDB('2i07')
pdb.calpha # error occurs here with any sort of selection

Error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda2\lib\site-packages\prody\atomic\atomic.py", line 72, in __getattribute__
    self._acsi, unique=True)
  File "C:\Anaconda2\lib\site-packages\prody\atomic\selection.py", line 29, in __init__
    AtomSubset.__init__(self, ag, indices, acsi, **kwargs)
  File "C:\Anaconda2\lib\site-packages\prody\atomic\subset.py", line 36, in __init__
    indices = list(indices[0])
TypeError: 'numpy.int64' object is not iterable

**Comment by cihankayacihan** [comment] 2016-04-22 16:49
Can you also share your operating system with version, python version please.

**Comment by PaolinoPaperino** [comment] 2016-05-03 10:39
Hello Everybody,

I have the same problem, it happens with any kind of selection and any calculation I try.

I am using Windows 10 with Python 2.7.10 and ProDy 1.7.

If you modify  indices = list(indices[0]) to  indices = [indices[0]] in subset.py the error disappears, as it seems that indices[0] is a single in64 number, but then any atom selection will give 1 atom and the program can't calculate anything out of it.

Let me know if you need more information and thanks for the help!

**Comment by reedharrison** [comment] 2016-05-03 17:09
Hello Cihankayacihan,

I am using Windows 10 with Python 2.7.11 [MSC v.1500 64 bit (AMD64)]. Thanks!

Hi Paolino,

Did this only fix the error, or were you able to perform atomic selections properly again? I think i tried something similar but it only fixed the error and selections were incorrect. I will try again later with your exact fix to test. Thanks!

**Comment by cihankayacihan** [comment] 2016-05-03 17:12
We tried that solution before but the selections were not working properly. Currently, we are trying to fix type issues related to indices. We will make a new release in this week and this issue will be fixed.

**Comment by PaolinoPaperino** [comment] 2016-05-05 11:22
Hello Reed,

unfortunately my attempt merely delayed the problem, so don't waste your time with it. It just shows you that list[0], which I am assuming is the list of selected atoms, is a single number instead of being a multiple selection and that the issue is upstream.

Hi Cihankayacihan,

glad to hear that, thanks for the help!

**Comment by SHZ66** [comment] 2016-05-12 18:57
Hi all, this issue should be fixed in #288. Please see the pull request and let me know if you still have the error.

**Comment by reedharrison** [comment] 2016-05-12 19:57
Hi,

The selection issue appears fixed for me now. However, perhaps I should mention that in setup.py I comment out the extensions for smtools, msatools, msaio, and seqtools in order to be able to install the library. In case you are wondering why, I have included the error below. Thanks again!

Error:
building 'prody.dynamics.rtbtools' extension
    creating build\temp.win-amd64-2.7
    creating build\temp.win-amd64-2.7\Release
    creating build\temp.win-amd64-2.7\Release\prody
    creating build\temp.win-amd64-2.7\Release\prody\dynamics
    C:\Users\Reed\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Anaconda2\lib\site-packages\numpy\core\include -IC:\Anaconda2\include -IC:\Anaconda2\PC /Tcprody\dynamics\rtbtools.c /Fobuild\temp.win-amd64-2.7\Release\prody\dynamics\rtbtools.obj
    rtbtools.c
    prody\dynamics\rtbtools.c(126) : warning C4244: '=' : conversion from 'double' to 'float', possible loss of data
    C:\Users\Reed\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\link.exe /DLL /nologo /INCREMENTAL:NO /LIBPATH:C:\Anaconda2\libs /LIBPATH:C:\Anaconda2\PCbuild\amd64 /LIBPATH:C:\Anaconda2\PC\VS9.0\amd64 /EXPORT:initrtbtools build\temp.win-amd64-2.7\Release\prody\dynamics\rtbtools.obj /OUT:build\lib.win-amd64-2.7\prody\dynamics\rtbtools.pyd /IMPLIB:build\temp.win-amd64-2.7\Release\prody\dynamics\rtbtools.lib /MANIFESTFILE:build\temp.win-amd64-2.7\Release\prody\dynamics\rtbtools.pyd.manifest
    rtbtools.obj : warning LNK4197: export 'initrtbtools' specified multiple times; using first specification
       Creating library build\temp.win-amd64-2.7\Release\prody\dynamics\rtbtools.lib and object build\temp.win-amd64-2.7\Release\prody\dynamics\rtbtools.exp
    building 'prody.dynamics.smtools' extension
    C:\Users\Reed\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Anaconda2\lib\site-packages\numpy\core\include -IC:\Anaconda2\include -IC:\Anaconda2\PC /Tcprody\dynamics\smtools.c /Fobuild\temp.win-amd64-2.7\Release\prody\dynamics\smtools.obj
    smtools.c
    prody\dynamics\smtools.c(49) : error C2143: syntax error : missing ';' before 'type'
    prody\dynamics\smtools.c(50) : error C2143: syntax error : missing ';' before 'type'
    prody\dynamics\smtools.c(51) : error C2143: syntax error : missing ';' before 'type'
    prody\dynamics\smtools.c(52) : error C2143: syntax error : missing ';' before 'type'
    prody\dynamics\smtools.c(53) : error C2143: syntax error : missing ';' before 'type'
    prody\dynamics\smtools.c(57) : error C2065: 'u_ij_sup_k' : undeclared identifier
    prody\dynamics\smtools.c(57) : error C2109: subscript requires array or pointer type
    prody\dynamics\smtools.c(60) : error C2065: 'u_ij_sup_k' : undeclared identifier
    prody\dynamics\smtools.c(60) : error C2109: subscript requires array or pointer type
    prody\dynamics\smtools.c(63) : error C2065: 'u_ij_sup_k' : undeclared identifier
    prody\dynamics\smtools.c(63) : error C2109: subscript requires array or pointer type
    prody\dynamics\smtools.c(65) : error C2065: 'cos_alpha_ij' : undeclared identifier
    prody\dynamics\smtools.c(65) : error C2065: 'u_ij_sup_k' : undeclared identifier
    prody\dynamics\smtools.c(65) : error C2109: subscript requires array or pointer type
    prody\dynamics\smtools.c(66) : error C2065: 'u_ij_sup_k' : undeclared identifier
    prody\dynamics\smtools.c(66) : error C2109: subscript requires array or pointer type
    prody\dynamics\smtools.c(67) : error C2065: 'u_ij_sup_k' : undeclared identifier
    prody\dynamics\smtools.c(67) : error C2109: subscript requires array or pointer type
    prody\dynamics\smtools.c(68) : error C2065: 'd_ij_sup_k' : undeclared identifier
    prody\dynamics\smtools.c(68) : error C2065: 'cos_alpha_ij' : undeclared identifier
    prody\dynamics\smtools.c(68) : warning C4244: '=' : conversion from 'double' to 'int', possible loss of data
    prody\dynamics\smtools.c(71) : error C2065: 'sum1' : undeclared identifier
    prody\dynamics\smtools.c(71) : error C2065: 'd_ij_sup_k' : undeclared identifier
    prody\dynamics\smtools.c(71) : warning C4244: '+=' : conversion from 'double' to 'int', possible loss of data
    prody\dynamics\smtools.c(72) : error C2065: 'sum2' : undeclared identifier
    prody\dynamics\smtools.c(72) : error C2065: 'd_ij_sup_k' : undeclared identifier
    prody\dynamics\smtools.c(72) : warning C4244: '+=' : conversion from 'double' to 'int', possible loss of data
    prody\dynamics\smtools.c(75) : error C2065: 'sum1' : undeclared identifier
    prody\dynamics\smtools.c(75) : error C2065: 'sum2' : undeclared identifier
    error: command 'C:\\Users\\Reed\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\cl.exe' failed with exit status 2

**Comment by cihankayacihan** [comment] 2016-05-12 20:13
Windows does not have gcc instead it has Visual C. You can not compile those in windows environment unless you have mingwc compiler or other form of gcc. The syntax has small differences in those two compilers. Therefore, you will have this issue. Currently, we are working on the release of new version. New windows installers will not have this problem.

**Comment by reedharrison** [comment] 2016-05-12 20:51
Ok, thanks.

**Comment by cihankayacihan** [comment] 2016-05-14 19:12
Version 1.8 for windows users is out. This issue is fixed now.

**Closed by cihankayacihan** 2016-05-14 19:12 UTC
Labels: Defect
