### ISSUE TITLE
Selecting a range of residues with insertion codes doesn't work

### ISSUE THREAD

**Issue by jonathanking** [prody/ProDy#1197] opened 2020-10-29 22:31 UTC
According to the docs, you can select a range of residues using `resnum X to Y`. It also says that you can specify the insertion code (i.e. `P` in this example) with `resnum XP`. However, `resnum XP to YP` doesn't work.

You can see that it parses the right insertion code, but the range doesn't work.

```python
>>> p = pr.parsePDB('1jqg', chain='A')
>>> s = p.select('resnum 4P to 100P')
>>> s.ca.getResnums()
array([  4, 100])
>>> s.ca.getIcodes()
array(['P', 'P'], dtype='<U1')
```

I have also found that this happens with pdb `1toc` and the selection `resnum 1A to 56`.

I did find this in the prody logger:
```log
WARNING  .prody:logger.py:141 WARNING Selection string contains typo(s):
                              'resnum 4P to 100P'
                                         ^ 'resnum' must be followed by integers, number ranges, or integer and insertion code combinations, e.g. '10A'
```

**Comment by jamesmkrieger** [comment] 2020-11-01 17:10
Hi Jonathan,

Thanks for reporting this. I'll have a look and see if I can fix it.

Best wishes
James

**Comment by jamesmkrieger** [comment] 2020-11-02 17:18
Hi Jonathan,

This is not a bug - it was just never an intended behaviour - is proving quite time-consuming to implement. Therefore, given that insertion codes don't work in a consistent way, I'd suggest you to select differently instead.

In the first case (1jqg), you could use `s = p.select('resnum 4 to 100 and icode P')` to select residues with numbers 4 to 100 inclusive and insertion code P.

In the second case (1toc), I'd suggest using `s = p.select('resnum 1 to 56 and not resnum 1B')` to select residues with numbers 1 to 56 and any insertion code but not select the residue with number + insertion code 1B, which precedes 1A.

Best wishes
James

**Comment by jamesmkrieger** [comment] 2020-11-02 17:19
You can also see from the warning that you need to supply either number ranges or number with insertion code combinations not both.

**Comment by jonathanking** [comment] 2020-11-02 19:55
Thanks for looking into this, @jamesmkrieger. I'll use the workaround you suggested.

As always, I appreciate your help! :)

**Comment by jamesmkrieger** [comment] 2020-11-03 12:15
You're welcome. I'll close the issue now.

**Closed by jamesmkrieger** 2020-11-03 12:15 UTC
