### ISSUE TITLE
getResnums only supports resnums up to 9999?

### ISSUE THREAD

**Issue by cgseitz** [prody/ProDy#1339] opened 2021-03-05 20:03 UTC
Hello, 

I am trying to get the residue numbers for the hinge sites in my system, which has >20,000 residues. However, getResnums only appears to support four digit numbers. I presume this from my results below, where they reach 9478 and then start back at 1225. You can also tell because it repeats 1472, presumably because it is not showing the last digit.
```
resnums = calphas.getResnums()
mode2_hinges = calcHinges(gnm[0])
resnums[mode2_hinges]
```

```
array([1343, 1349, 1678, 1908, 1918, 2002, 2004, 2218, 2234, 2803, 5569,
       8017, 8026, 8110, 8112, 8324, 8558, 8565, 8911, 9462, 9478, 1225,
       1472, 1472, 1481, 1505, 1528, 1529, 1538, 1562, 1564, 1845, 2013,
       2016, 2018, 2026, 2033, 2036])
```

This is also suggested because looking at the residue names, the first 1472 is GLY1472 and the second is GLU1472.

```
resnames = calphas.getResnames()
resnames[mode2_hinges]
```
```
array(['GLN', 'GLU', 'GLY', 'ASN', 'THR', 'THR', 'VAL', 'GLY', 'GLY',
       'GLY', 'ALA', 'GLY', 'THR', 'THR', 'VAL', 'SER', 'GLN', 'GLU',
       'GLY', 'GLY', 'GLY', 'ASN', 'GLY', 'GLU', 'GLY', 'GLY', 'GLY',
       'THR', 'VAL', 'GLY', 'GLY', 'GLY', 'ALA', 'ALA', 'ALA', 'ALA',
       'ALA', 'SER'], dtype='<U6')
```

**Comment by jamesmkrieger** [comment] 2021-03-06 16:21
You're right. Resnums only supports 4 digits. I have a system with more residues too and have reproduced that after 9999, the next residue is 1000 instead of 10000. 

The problem is which columns of the PDB file are being read. Strictly speaking, a PDB file can't have a residue number with more than 4 columns (22:26) and ProDy reads it accordingly. The last digit (column 26 in python) is actually an insertion code and ProDy reads it as such, which is how PyMOL and VMD read it too (in fact this causes problems for writing the PDB file back out of PyMOL because it reorders the atoms to put 10000 (1000 with insertion code 0) after 1000 unless you check the box saying to retain atom orders). 

Having an extra column of number by using the insertion code is in fact a trick that was employed in writing these files (I think it was CHARMM-GUI that did it but other programs may too) so what we can do is use the same trick for reading the files. 
The code would then check if the insertion code is a number and combine it into the residue number if it is, I suppose. This is, however, an issue for users who don't expect that to happen. What do you think?

**Comment by jamesmkrieger** [comment] 2021-03-06 16:34
Was your file from CHARMM-GUI too? I think systems prepared in VMD have hexadecimal residue numbers instead.

**Comment by cgseitz** [comment] 2021-03-08 03:29
Yes, I think there should be a warning somewhere so users do not use too large of pdb files and don't realize that it may not be fully read. I created my pdb through tleap, but the pdb numbering is indeed a bit wonky in mine. Do you know any ways I can modify my pdb to be properly read? Or can the code be modified?

**Comment by jamesmkrieger** [comment] 2021-03-08 08:03
I suppose if we make this change in ProDy to read these files then you can write new ones back out with hexadecimal or hybrid36 numbers

**Comment by jamesmkrieger** [comment] 2021-03-08 16:18
Actually, ProDy is not handling handling resnum length for assessing when to write hexadecimal or hybrid36 so I'll fix that too.

**Comment by jamesmkrieger** [comment] 2021-03-08 16:32
It's only converting serial numbers so I'll fix that too.

**Comment by jamesmkrieger** [comment] 2021-03-08 17:30
Ok, fixed. Now you should be able to use ProDy for writing to hexadecimal or hybrid36.

**Comment by jamesmkrieger** [comment] 2021-03-08 17:43
This is actually quite an interesting issue so thanks Christian for raising it.

**Comment by cgseitz** [comment] 2021-03-09 07:36
You're welcome, and thank you for fixing it! It looks like your updates have been merged, but my notebook still does not look different. Is there a specific way I should be installing prody from github that isn't mentioned in the installation instructions? Since I don't have sudo access I have been installing prody by conda install, then exporting my python path to the miniconda/bin, followed by adding this to my jupyter notebook:
```
import sys
!{sys.executable} -m pip install prody --user
from prody import *
```

**Comment by jamesmkrieger** [comment] 2021-03-09 08:55
Hi Christian,

My updates have not been merged yet. I’ve still got a little bit more to do first including making tests. I’ll let you know when it is.

Yes, there are instructions on installing from GitHub under the developer’s section of the manual, which you can find on the tutorials page next to the main ProDy tutorial. The direct link is http://prody.csb.pitt.edu/manual/devel/develop.html

As an alternative to building in place and using the $PYTHONPATH environment variable, you can also use

pip install -U .

You may need to put —user on the end if you don’t have sudo but shouldn’t have depending how your python environment is set up.

Best wishes 
James

**Comment by jamesmkrieger** [comment] 2021-03-09 08:56
Basically you could continue doing the same as what you did but replacing prody with . for the current directory that comes from GitHub

**Comment by jamesmkrieger** [comment] 2021-03-09 13:55
I'm very almost there now. If these tests pass then I will merge it.

Thanks for your patience.

**Comment by jamesmkrieger** [comment] 2021-03-09 14:58
The Python 2.7 test now passed too (there were initially some problems with that) and the Python 3.8 one should do soon seeing as it did previously.

**Comment by jamesmkrieger** [comment] 2021-03-09 18:27
It's now merged so you should be able to pull and install it now.

**Closed** 2021-03-11 12:18 UTC

**Comment by cgseitz** [comment] 2021-03-12 01:52
Thank you!! Sorry for the delay, I was trying to find an installation that worked and would show your new updates. In the end, creating a new conda environment succeeded where all the others failed~

**Comment by jamesmkrieger** [comment] 2021-03-12 06:59
Oh ok. Glad you got it working
