### ISSUE TITLE
@> WARNING Matplotlib could not be imported. Figures are not saved.

### ISSUE THREAD

**Issue by Mira2121** [prody/ProDy#1736] opened 2023-08-16 19:49 UTC
Hi, I'm using prody on linux, have =installed as per guidelines, including matplotlib (pip install matplotlib). When trying to calculate pca, (command: prody pca trajectory.dcd --pdb protein.pdb --aligned -a -A), it does not save the figures. Following is the output report of the aforementioned command: 
@> 1000 atoms and 1 coordinate set(s) were parsed in 0.27s.
@> 400 atoms are selected for calculations.
@> Covariance will be calculated using 2000 frames.
@> Covariance matrix calculated in 137.213672s.
@> 10 modes were calculated in 0.90s.
@> Writing numerical output.
@> WARNING Matplotlib could not be imported. Figures are not saved.
Why can matplotlib not be imported?
Thanks

**Comment by jamesmkrieger** [comment] 2023-08-16 20:33
Have you definitely got the right environment activated with everything installed in there?

If so, I’m not sure

**Comment by jamesmkrieger** [comment] 2023-08-16 20:33
Can you provide more information about the installation and running please

**Comment by jamesmkrieger** [comment] 2023-11-05 18:24
As I haven't got any further replies and am not able to reproduce this error without more info, I am closing it for now. Please feel free to open it again.

**Closed by jamesmkrieger** 2023-11-05 18:24 UTC
