### ISSUE TITLE
Mechanical Stiffness in VMD errata

### ISSUE THREAD

**Issue by MollyGravett** [prody/ProDy#786] opened 2018-12-17 12:39 UTC
`writeDeformProfile(anm, gfp, selstr='chain A and name CA', pdb_selstr='protein')`

should be:
`writeDeformProfile(anm, gfp, select='chain A and name CA', pdb_selstr='protein')`

**Comment by MollyGravett** [comment] 2018-12-17 13:07
even with correction get this error message:

  **File "~/anaconda3/lib/python3.7/site-packages/numpy/core/_methods.py", line 87, in _mean
    ret = ret / rcount**

**TypeError: unsupported operand type(s) for /: 'Vector' and 'int'**

**Comment by jamesmkrieger** [comment] 2019-01-21 01:03
I think this problem is because you're using python-3 and this function hasn't been updated to be python3-compatible.

**Comment by jamesmkrieger** [comment] 2019-01-21 01:03
John, can you fix that please.

**Comment by jamesmkrieger** [comment] 2019-07-25 23:37
Thanks Molly for spotting that. I have now fixed the website repo (see prody/prody-website#49). 

We'll still need to look into what's happening with the numpy error.

**Comment by jamesmkrieger** [comment] 2020-04-14 17:28
Can you see if a numpy update fixes it?

**Comment by jamesmkrieger** [comment] 2020-05-22 10:41
I think actually the problem is that we shouldn't be providing `anm` to writeDeformProfile.

**Comment by jamesmkrieger** [comment] 2020-05-22 10:51
I've now fixed the website on a pull request so this issue is closed.

**Closed by jamesmkrieger** 2020-05-22 10:51 UTC
