### ISSUE TITLE
Evol application. Several issues

### ISSUE THREAD

**Issue by gtzotzos** [prody/ProDy#773] opened 2018-11-09 18:52 UTC
ProDy is now upgraded to **1.10.8**

evol search 2w5i results in: 
@> PDB file is found in working directory (2w5i.pdb.gz).
@> WARNING A UniProt ID code for PDB '2W5IB' could not be parsed.
@> Retrieving Pfam search results: https://pfam.xfam.org/protein/2W5IB?output=xml
@> Pfam search completed in 0.98s.
@> PDB file is found in working directory (2w5i.pdb.gz).
@> 124 atoms and 1 coordinate set(s) were parsed in 0.01s.
@> Submitted Pfam search for sequence "KETAAAKFERQHMDSS...".
:::::::::
**UnboundLocalError: local variable 'accession' referenced before assignment**
During handling of the above exception, another exception occurred:
:::::::::
**TypeError: a bytes-like object is required, not 'str'**

During handling of the above exception, another exception occurred:
:::::::::
**ValueError: No valid UniProt accession or ID for: 2W5IB**

2. The command: **evol coevol PF00074_full_refined.slx -S** works

but the command **evol coevol PF00074_full_refined.slx -S -F png -c apc -cmin 0.0** gives the following error: **argument -c/--correction: invalid choice: 'min' (choose from 'apc', 'asc')**

**Comment by gtzotzos** [comment] 2018-11-13 17:45
Thank you for the prompt reply.

Python **3.6.4**
IPython **6.2.1**

The command issued for case 1 is: **evol search 2W5IB**
the output of which is:
@> PDB file is found in working directory (2w5i.pdb.gz).
@> WARNING A UniProt ID code for PDB '2W5IB' could not be parsed.
@> Retrieving Pfam search results: https://pfam.xfam.org/protein/2W5IB?output=xml
@> Pfam search completed in 0.40s.
@> PDB file is found in working directory (2w5i.pdb.gz).
@> 124 atoms and 1 coordinate set(s) were parsed in 0.01s.
@> Submitted Pfam search for sequence "KETAAAKFERQHMDSS...".
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/prody/database/pfam.py", line 222, in searchPfam
    url = prefix + 'protein/' + accession + '?output=xml'
UnboundLocalError: local variable 'accession' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/prody/database/pfam.py", line 228, in searchPfam
    return searchPfam(ag_seq)
  File "/anaconda3/lib/python3.6/site-packages/prody/database/pfam.py", line 134, in searchPfam
    lines = tsv.split('\n')
TypeError: a bytes-like object is required, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/prody/apps/apptools.py", line 281, in callback
    func(*args, **ns.__dict__)
  File "/anaconda3/lib/python3.6/site-packages/prody/apps/evol_apps/evol_search.py", line 90, in evol_search
    pfam_results =  prody.searchPfam(query, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/prody/database/pfam.py", line 230, in searchPfam
    raise ValueError('No valid UniProt accession or ID for: ' + seq)
ValueError: No valid UniProt accession or ID for: 2W5IB
An exception occurred when executing your command.  If this is not a user error, please report it to ProDy developers at: https://bitbucket.org/abakan/prody/issues
Error: No valid UniProt accession or ID for: 2W5IB

**Comment by gtzotzos** [comment] 2018-11-13 17:46
Thank you for the prompt reply.

Python **3.6.4**
IPython **6.2.1**

The command issued for case 1 is: **evol search 2W5IB**
the output of which is:
@> PDB file is found in working directory (2w5i.pdb.gz).
@> WARNING A UniProt ID code for PDB '2W5IB' could not be parsed.
@> Retrieving Pfam search results: https://pfam.xfam.org/protein/2W5IB?output=xml
@> Pfam search completed in 0.40s.
@> PDB file is found in working directory (2w5i.pdb.gz).
@> 124 atoms and 1 coordinate set(s) were parsed in 0.01s.
@> Submitted Pfam search for sequence "KETAAAKFERQHMDSS...".
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/prody/database/pfam.py", line 222, in searchPfam
    url = prefix + 'protein/' + accession + '?output=xml'
UnboundLocalError: local variable 'accession' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/prody/database/pfam.py", line 228, in searchPfam
    return searchPfam(ag_seq)
  File "/anaconda3/lib/python3.6/site-packages/prody/database/pfam.py", line 134, in searchPfam
    lines = tsv.split('\n')
TypeError: a bytes-like object is required, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/prody/apps/apptools.py", line 281, in callback
    func(*args, **ns.__dict__)
  File "/anaconda3/lib/python3.6/site-packages/prody/apps/evol_apps/evol_search.py", line 90, in evol_search
    pfam_results =  prody.searchPfam(query, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/prody/database/pfam.py", line 230, in searchPfam
    raise ValueError('No valid UniProt accession or ID for: ' + seq)
ValueError: No valid UniProt accession or ID for: 2W5IB
An exception occurred when executing your command.  If this is not a user error, please report it to ProDy developers at: https://bitbucket.org/abakan/prody/issues
Error: No valid UniProt accession or ID for: 2W5IB

**Comment by gtzotzos** [comment] 2018-12-18 18:23
Hi again,

I checked once again and the problem persists. Any ideas for a work around would be appreciated.

Thanks in advance

**Comment by jamesmkrieger** [comment] 2018-12-18 20:04
We don't update the apps much so I imagine there are lots of problems with using them with python 3. Can you try using python 2 and see if you still have problems.

Best wishes
James

**Comment by gtzotzos** [comment] 2019-01-23 15:34
Thank you James.

I've conducted extensive troubleshooting and the problem is indeed with the use of **Python 3**, which uses the **bytes type** instead of the **str type**. 

I've reinstalled the prody and evol programs in a clean Python 2.7 environment and evol works fine ... **or almost fine**. I tried the evol application as per http://prody.csb.pitt.edu/tutorials/evol_tutorial/evolapps.html.
Here's some of the problems that I've encountered.  

**1.** evol coevol PF00074_full_refined.slx -S -F png -c apc -cmin 0.0 doesn't work. 
Removing -cmin 0.0 works.
**2.** evol rankorder PF00074_full_refined_mutinfo_corr_apc.txt -q 5 -p 2W5IB_1-121.pdb
@> **Could not parse PDB, ignoring PDB input**
@> MSA or PDB not given or does not match mutinfo, using serial indexing
@> Residue numbers start and end with 1-119
(trivial error of the site: remove the 2nd "I" from -p 2W5IBI_1-121.pdb)
3. I tried evol rankorder PF00074_full_refined_mutinfo_corr_apc.txt -q 5 -p 2W5IB_1-119.pdb
This also gives  **Could not parse PDB, ignoring PDB input**
4. evol rankorder PF00074_full_refined_mutinfo_corr_apc.txt -u -t 15 -p 2W5IB_1-121.pdb # or **1-119**
@> **Could not parse PDB, ignoring PDB input**
@> MSA or PDB not given or does not match mutinfo, using serial indexing
@> Residue numbers start and end with 1-119
@> **use-struct-sep set to true, but PDB not given or incorrect residue number. Using sequence separation**

I hope this helps

George

**Comment by jamesmkrieger** [comment] 2019-02-19 04:16
Do you have these PDB files in your directory? Where do they come from?

**Comment by jamesmkrieger** [comment] 2019-02-19 04:20
It's great to hear python 2.7 basically works. I think I can deal with the bytes vs str issue some time in the next few weeks. We're in the middle of revising a paper and then I need to prepare something for the biophysical society annual meeting. I can try and have a look when I get back. Probably all the apps need an overhaul for python 3 and I'll look into these other problems too.

Thanks for the detailed investigation and report.

**Comment by jamesmkrieger** [comment] 2019-03-29 16:52
I'm almost ready to look at the apps I think. I'll start with issues that already exist in python2 such as the one you mentioned in your last post and then move on to python3 afterwards.

Best wishes
James

**Comment by jamesmkrieger** [comment] 2019-07-25 23:42
There are still lots of things to do so I'm sorry this issue is still there.

**Comment by jamesmkrieger** [comment] 2020-09-02 00:48
Again, part of the issue is that this PDB file doesn't exist so I've added about writing it in the tutorial.

**Comment by jamesmkrieger** [comment] 2020-09-02 02:15
It looks like part of this was also fixed by https://github.com/prody/ProDy/pull/987

**Comment by jamesmkrieger** [comment] 2020-09-02 02:16
There were also a number of problems with the evol apps tutorial online, including `-cmin` should be `--cmin` with two hyphens.

**Comment by jamesmkrieger** [comment] 2020-09-02 02:23
The correct input and output should be the following:
```
$ evol search 2W5IB
@> PDB file is found in the local folder (C:\Users\james\...\2w5i.pdb.gz).
@> UniProt ID code RNAS1_BOVIN for 2W5I chain B will be used.
@> Retrieving Pfam search results: https://pfam.xfam.org/protein/RNAS1_BOVIN?output=xml
@> Pfam search completed in 0.39s.
@> Query '2W5IB' matched 1 Pfam families.
acc     id      type    e-value
PF00074 RnaseA  Pfam-A  4.8e-40

$ evol fetch PF00074
@> Pfam MSA for PF00074 is written as .\PF00074_full.slx.

$ evol refine PF00074_full.slx -l RNAS1_BOVIN -s 0.98 -r 0.8
@> 1187 sequence(s) with 316 residues were parsed in 0.02s.
@> Label refinement reduced number of columns from 316 to 119 in 0.00s.
@> Row occupancy refinement reduced number of rows from 1187 to 1042 in 0.00s.
@> Sequence identity refinement reduced number of rows from 1042 to 857 in 0.12s.
@> Refined MSA is written in file: PF00074_full_refined.slx

$ evol conserv PF00074_full_refined.slx -S
@> 857 sequence(s) with 119 residues were parsed in 0.02s.
@> Cannot parse label start, end values, Setting resnums 1 to 119

$ evol coevol PF00074_full_refined.slx -S -F png -c apc --cmin 0.0
@> 857 sequence(s) with 119 residues were parsed in 0.02s.
@> Mutual information matrix was calculated in 0.02s.
@> Cannot parse label start, end values, Setting resnums 1 to 119
@> Applying 'apc' correction.
@> Cannot parse label start, end values, Setting resnums 1 to 119

$ prody fetch 2W5I
@> PDB file is found in the local folder (2w5i.pdb).

$ prody select 'ca and chain B and resnum 3 to 121' 2w5i.pdb -o 2W5IB_3-121.pdb
@> 1921 atoms and 1 coordinate set(s) were parsed in 0.02s.
@> Selection 'ca and chain B and resnum 3 to 121' matched 119 atoms.
@> Selection is written into: 2W5IB_3-121.pdb

$ evol rankorder PF00074_full_refined_mutinfo_corr_apc.txt -q 5 -p 2W5IB_3-121.pdb
@> 119 atoms and 1 coordinate set(s) were parsed in 0.00s.
@> Residue numbers will be based on pdb: 2W5IB_3-121
@> Residue numbers start and end with 3-121
@> use-dist not set, using sequence separation to report coevolving pairs
```

My output file now starts as follows:
```
Label: 2W5IB_3-121	Residue Numbers: 3-121	Sequence Separation:5
Serial	Row	Column	MI	Distance
1	72	65	0.513	5.44
2	82	48	0.483	7.81
3	25	14	0.267	11.20
4	109	71	0.266	5.51
```

**Comment by jamesmkrieger** [comment] 2020-09-02 02:25
Please see my fixes at https://github.com/prody/ProDy/pull/1138 and the tutorial fixes at https://github.com/prody/ProDy-website/pull/65

**Closed** 2020-09-02 02:25 UTC
Labels: Apps
