### ISSUE TITLE
PCA Percent Contribution

### ISSUE THREAD

**Issue by william61001** [prody/ProDy#1408] opened 2021-09-18 20:08 UTC
Hello, I am new to using ProDy so I apologize if this is a trivial question. I ran a PCA calculation on my system which gave me ten principal components, but I can't find a way to see the percent contribution of each PC. Is there any way of doing this? It would allow me to see how my PC1 compares to the other PCs. Any help would be appreciated!

**Comment by jamesmkrieger** [comment] 2021-09-18 20:19
Yes, the function is called calcFractVariance and then you can multiply by 100 to get a percentage

**Comment by william61001** [comment] 2021-09-18 21:18
Is there any way to do that using the Normal Mode Wizard? That is how I have been doing my PCA calculations. Thanks.

**Comment by jamesmkrieger** [comment] 2021-09-20 09:51
Yes but not easily. The scaling factors for the modes are the square roots of the variances so what you can do is divide the square of each one by the sum of the squares. 

Again, I'd prefer to do that with Python with code such as the following:
```
In [36]: scales = np.array([154.4, 37.75, 22.42, 16.26, 14.63, 10.02, 9.01, 8.57, 6.62, 5.32, 5.24, 4.37, 3.94, 3.35, 3.04, 2.69, 1.91])

In [37]: (scales[0]**2)/np.sum(np.square(scales))
Out[37]: 0.8939956008535487
```

You could also do it with a calculator or by hand though.

**Comment by jamesmkrieger** [comment] 2021-09-20 09:57
Python is very helpful for this. I can get my whole set of values with a list comprehension:
```
In [40]: fractVars = [(s**2)/np.sum(np.square(scales)) for s in scales]

In [41]: fractVars
Out[41]:
[0.8939956008535487,
 0.05344101544426361,
 0.018850028286870192,
.
.
.
```

We can also confirm that these values are the same as those from calcFractVariance in ProDy:
```
In [42]: fractVars[:5]
Out[42]:
[0.8939956008535487,
 0.05344101544426361,
 0.018850028286870192,
 0.009914752380945954,
 0.00802655973232213]

In [43]: calcFractVariance(pca_B)[:5]
Out[43]: array([0.89407362, 0.05340363, 0.01884203, 0.00990205, 0.00801793])
```

There are some rounding errors because we only had the scaling factors to 4 significant figures, but they're small enough to not matter. We can still quote the percentage variances as 89.4 %, 5.34 %, 1.88 % and so on and not worry about the finer details.

**Comment by jamesmkrieger** [comment] 2021-09-20 09:58
Python and ProDy does have lots of other nice features though such as showFractVars, which shows them on a bar graph such as the one attached. 
![PCA_fract_vars](https://user-images.githubusercontent.com/13259162/133984820-e5915786-1979-48fd-b938-70461e487026.png)

**Comment by jamesmkrieger** [comment] 2021-09-20 09:59
We may want to consider this as a feature request for NMWiz so I'll leave it open for now. Probably we won't change that though.

**Comment by TianmingQu** [comment] 2022-01-20 21:25
> Python and ProDy does have lots of other nice features though such as showFractVars, which shows them on a bar graph such as the one attached. ![PCA_fract_vars](https://user-images.githubusercontent.com/13259162/133984820-e5915786-1979-48fd-b938-70461e487026.png)

Hi,

How do you print out this plot?

Best,
Tianming

**Comment by jamesmkrieger** [comment] 2022-01-21 07:15
import matplotlib.pyplot as plt
plt.ion()

plt.figure()
showFractVars(pca)
plt.savefig(“pca_fract_vars.png”)

**Comment by araichow** [comment] 2024-01-24 18:54
> Python is very helpful for this. I can get my whole set of values with a list comprehension:
> 
> ```
> In [40]: fractVars = [(s**2)/np.sum(np.square(scales)) for s in scales]
> 
> In [41]: fractVars
> Out[41]:
> [0.8939956008535487,
>  0.05344101544426361,
>  0.018850028286870192,
> .
> .
> .
> ```
> 
> We can also confirm that these values are the same as those from calcFractVariance in ProDy:
> 
> ```
> In [42]: fractVars[:5]
> Out[42]:
> [0.8939956008535487,
>  0.05344101544426361,
>  0.018850028286870192,
>  0.009914752380945954,
>  0.00802655973232213]
> 
> In [43]: calcFractVariance(pca_B)[:5]
> Out[43]: array([0.89407362, 0.05340363, 0.01884203, 0.00990205, 0.00801793])
> ```
> 
> There are some rounding errors because we only had the scaling factors to 4 significant figures, but they're small enough to not matter. We can still quote the percentage variances as 89.4 %, 5.34 %, 1.88 % and so on and not worry about the finer details.

May I please ask if the (pca_B) argument in your calcFractVariance derived from pca_B=parseNMD('path to your .nmd file which was output of pca analysis done using VMD')? I am getting an error message of  "raise TypeError('mode must be a Mode instance')
TypeError: mode must be a Mode instance"

**Comment by jamesmkrieger** [comment] 2024-01-24 22:10
The problem is that parseNMD gives a tuple of (pca, atoms). So the command should be like this.

pca, atoms = parseNMD('./L11_nowater_gro_pca.nmd')

Sorry for not explaining that before.

Best wishes 
James

**Comment by araichow** [comment] 2024-01-24 22:28
Thanks a lot, James! That worked perfectly. And no worries at all!

**Comment by jamesmkrieger** [comment] 2024-01-24 22:42
I don’t think we’ll update nmwiz so as that’s solved, I’m closing the issue

**Closed by jamesmkrieger** 2024-01-24 22:42 UTC
Labels: Feature request

**Comment by araichow** [comment] 2024-01-25 16:17
Okay! Just knowing this parseNMD syntax makes a huge difference. 

Another NMWIZ issues I am facing is that for every new PCA calculation with a new .gro loaded with .xtc I have to do _**conda activate prody_env**_  on the same terminal and open VMD again. However since doing that is working, I am not worrying about solving that for now.

**Comment by jamesmkrieger** [comment] 2024-01-25 16:41
There is a lot of documentation on the prody website e.g. http://prody.csb.pitt.edu/manual/reference/dynamics/nmdfile.html?highlight=parsenmd#prody.dynamics.nmdfile.parseNMD

parseNMD(filename, type=<class 'prody.dynamics.nma.NMA'>)[[source]](http://prody.csb.pitt.edu/_modules/prody/dynamics/nmdfile.html#parseNMD)
Returns [NMA](http://prody.csb.pitt.edu/manual/reference/dynamics/nma.html#prody.dynamics.nma.NMA) and [AtomGroup](http://prody.csb.pitt.edu/manual/reference/atomic/atomgroup.html#prody.atomic.atomgroup.AtomGroup) instances storing data parsed from filename in .nmd format. Type should be [NMA](http://prody.csb.pitt.edu/manual/reference/dynamics/nma.html#prody.dynamics.nma.NMA) or a subclass such as [PCA](http://prody.csb.pitt.edu/manual/reference/dynamics/pca.html#prody.dynamics.pca.PCA), [ANM](http://prody.csb.pitt.edu/manual/reference/dynamics/anm.html#prody.dynamics.anm.ANM), or [GNM](http://prody.csb.pitt.edu/manual/reference/dynamics/gnm.html#prody.dynamics.gnm.GNM).

I'm surprised you have to keep doing that but if it works then oh well. Does it not work deleting the current molecule and loading the new one into the same window?

**Comment by araichow** [comment] 2024-01-25 17:12
Hi James,

I did read those two lines on parseNMD so many times yesterday, but my lack of experience so far probably is why I did not see the adding , atoms in the syntax as a solution!
Now I know when something says it returns __ and __ I should consider my variable before the = as well.

Yeah, deleting the molecule is not helping. But starting it over is working! So, I am also like, oh well! And it is in my protocol so my lab mates will also know that solution when they need it.

Thanks,
Anu



________________________________

**Comment by jamesmkrieger** [comment] 2024-01-25 17:31
ok

Yes, sometimes it's not as clear as it could be and that's probably one of the better ones.

As I said, the best way is usually to check things as you go, e.g.
```
>>> x = parseNMD("/home/jkrieger/ScipionUserData/projects/test_build_full_v3/Runs/001572_ProDyLDA/modes.nmd")
>>> x
(<NMA: Unknown (1 modes; 2724 atoms)>, <AtomGroup: Unknown (2724 atoms)>)
```
