### ISSUE TITLE
Atom selection bug with p.select('hetero')

### ISSUE THREAD

**Issue by JianyuLi19** [prody/ProDy#913] opened 2019-08-15 16:18 UTC
Hi everyone,
I have ProDy 1.10.8 installed on my machine running Ubuntu 18.04 (64 bit). 
When trying to use the ProDy to select heteroatoms with p.select('hetero'), I got the following error message wenn the heteroatoms are from one of the following ligands:
['ATP', 'ADP', 'ADE', 'AMP', 'UTP', 'UDP', 'UMP', 'GTP', 'GDP', 'GMP'].

>>>pl_complex = parsePDB(file_path)
>>>ca = pl_complex.select('calpha')
>>>hetero = pl_complex.select(not water and hetero)
>>>pl = ca + hetero

Traceback (most recent call last):
  File "test.py", line 32, in <module>
    pl = ca + hetero
  File "/home/jianyu/anaconda3/envs/score/lib/python2.7/site-packages/prody/atomic/pointer.py", line 141, in __add__
    repr(type(other).__name__)))
TypeError: unsupported operand type(s) for +: 'Selection' and 'NoneType'

Although manually changing the name of these ligands to UNK works fine. 

Original pdb file: not working.
HETATM 6695  PG  ATP A 461     -25.333 -18.121  18.158  1.00 72.12           P  
HETATM 6696  O1G ATP A 461     -23.965 -17.806  17.603  1.00 71.43           O  
HETATM 6697  O2G ATP A 461     -26.423 -18.212  17.117  1.00 71.65           O  
HETATM 6698  O3G ATP A 461     -25.351 -19.235  19.178  1.00 71.97           O  
HETATM 6699  PB  ATP A 461     -24.662 -15.606  19.177  1.00 71.36           P  
HETATM 6700  O1B ATP A 461     -23.632 -16.020  20.201  1.00 70.43           O  

Modified pdb file: working.
HETATM 6695  PG  UNK A 461     -25.333 -18.121  18.158  1.00 72.12           P  
HETATM 6696  O1G UNK A 461     -23.965 -17.806  17.603  1.00 71.43           O  
HETATM 6697  O2G UNK A 461     -26.423 -18.212  17.117  1.00 71.65           O  
HETATM 6698  O3G UNK A 461     -25.351 -19.235  19.178  1.00 71.97           O  
HETATM 6699  PB  UNK A 461     -24.662 -15.606  19.177  1.00 71.36           P  
HETATM 6700  O1B UNK A 461     -23.632 -16.020  20.201  1.00 70.43           O  

Thanks
Jianyu

**Comment by jamesmkrieger** [comment] 2019-08-16 01:13
Hi Jianyu,

I think the problem is that you don't have quotes around `not water and hetero` on your third code line. 

Please try changing this and let us know if that fixes it.

Best wishes
James

**Comment by JianyuLi19** [comment] 2019-08-16 10:22
> Hi Jianyu,
> 
> I think the problem is that you don't have quotes around `not water and hetero` on your third code line.
> 
> Please try changing this and let us know if that fixes it.
> 
> Best wishes
> James

Hi James,
thanks for your reply. Sorry I have the wrong version here, in my script I have quotes around '`not water and hetero'. I just copy the code again:

>>> pl_complex = parsePDB(file_path)
>>>ca = pl_complex.select('calpha')
>>>hetero = pl_complex.select('not water and hetero')
>>>pl = ca + hetero

Today I just found one more ligand name for which it is also not working: 'ADK', so the new list will be: 
['ATP', 'ADP', 'ADE', 'ADK', 'AMP', 'UTP', 'UDP', 'UMP', 'GTP', 'GDP', 'GMP']

Thanks and best,
Jianyu

**Comment by jamesmkrieger** [comment] 2019-08-21 01:00
Oh, I see. Thanks Jianyu. We'll need to look into that.

It could be that those aren't treated as hetero atoms because they are also part of RNA. 

You might be better to use `ligand = pdb.select('not protein and not water')` as in http://prody.csb.pitt.edu/tutorials/structure_analysis/ligands.html

**Comment by jamesmkrieger** [comment] 2019-08-21 01:19
You can also use `hetero = pl_complex.select('hetatm and not water')`. This works fine for me with a test case that I found in the PDB that contains ADE:

```
In [6]: aha = parsePDB('1aha')

In [22]: aha.select('hetatm and not water').getResnames()                                                                                                       
Out[22]: 
array(['ADE', 'ADE', 'ADE', 'ADE', 'ADE', 'ADE', 'ADE', 'ADE', 'ADE',
       'ADE'], dtype='<U6')
```

**Comment by jamesmkrieger** [comment] 2020-03-25 18:14
I think I found the answer. In the flag file, we have some definitions and this is what it says for hetero:

   hetero
      indicates anything other than a :term:`protein` or a
      :term:`nucleic` residue, i.e. ``'not (protein or nucleic)'``.

In other words, this cannot select a ligand residue that is of the same type as a protein or nucleic residue by definition. If you want to select those you should use `hetatm` instead of `hetero`.

I do not think it would be a good idea to change these definitions at this point when there are probably a number of users who use them. 

Do you agree you have an alternative and the case can be closed?

**Comment by jamesmkrieger** [comment] 2020-04-14 10:30
I'm assuming this is fine now and closing it.

**Closed by jamesmkrieger** 2020-04-14 10:30 UTC

**Comment by JianyuLi19** [comment] 2020-04-14 10:36
> I think I found the answer. In the flag file, we have some definitions and this is what it says for hetero:
> 
> hetero
> indicates anything other than a :term:`protein` or a
> :term:`nucleic` residue, i.e. `'not (protein or nucleic)'`.
> 
> In other words, this cannot select a ligand residue that is of the same type as a protein or nucleic residue by definition. If you want to select those you should use `hetatm` instead of `hetero`.
> 
> I do not think it would be a good idea to change these definitions at this point when there are probably a number of users who use them.
> 
> Do you agree you have an alternative and the case can be closed?

Hi James, thank you very much for the very useful information! It's working for me now!
