### ISSUE TITLE
Can't parse PSF

### ISSUE THREAD

**Issue by USER762341** [prody/ProDy#268] opened 2015-12-16 23:25 UTC
I'm having issues parsing this PSF file with parsePSF (psffile.py).

[psf.zip](https://github.com/prody/ProDy/files/64698/psf.zip)

Looks like a bad calculation in line 66: lines = psf.readlines(71 * (n_atoms + 5))

I'm not really sure what that expression is for, but it's returning a very low number of lines compared to how many lines are really in the file.

**Comment by cihankayacihan** [comment] 2016-04-22 20:13
can you share the error message, your python version and operating system version.

**Comment by SHZ66** [comment] 2016-05-17 22:23
Hi, the problem is that the provided psf file has more than 71 characters per line which usually is the case. I modified the code to fit such situations, so it should be fixed in #302.

**Closed** 2016-05-18 01:59 UTC
