### ISSUE TITLE
Calling WritePSF after selecting a subset of the atoms loses Donors, Acceptors, Crossterms

### ISSUE THREAD

**Issue by GregorySchwing** [prody/ProDy#1514] opened 2022-03-28 08:27 UTC
Calling WritePSF after selecting a subset of the atoms by a distance criterion loses Donors, Acceptors, Cross and fails midway through writing.

I have attached a full example.  I am trying to merge a protein and an existing solvent box.  I am successfully superimposing the protein in the center of the solvent.  Then I use the convenient "+" concatenation to create a single atom group.  I write this to psf and pdb.  I reload these and do distance based selection to remove waters too close to the protein.  When I try to write the psf of the selection I get the following error:
@> WARNING donors are not set, use `AtomGroup.setDonors`
Traceback (most recent call last):
  File "merP.py", line 38, in <module>
    writePSF("final.psf", badwatersPSF)
  File "/home/greg/anaconda3/envs/mosdef-study38/lib/python3.8/site-packages/prody/trajectory/psffile.py", line 380, in writePSF
    donors = list(atoms._iterDonors())
  File "/home/greg/anaconda3/envs/mosdef-study38/lib/python3.8/site-packages/prody/atomic/pointer.py", line 439, in _iterDonors
    for a, dmap in zip(indices, self._ag._domap[indices]):
TypeError: 'NoneType' object is not subscriptable

I am welcome to learn how to do this another way if necessary

Thanks.

**Comment by GregorySchwing** [comment] 2022-03-28 08:27
[issue.zip](https://github.com/prody/ProDy/files/8360985/issue.zip)

**Comment by jamesmkrieger** [comment] 2022-03-28 18:54
This definitely sounds like the reasonable way to do things and even if there were better ones this should work.

I’ll try to have a look soon. 

Thanks for the detailed reporting of it

**Comment by GregorySchwing** [comment] 2022-03-28 22:06
[merP2Functional.py.zip](https://github.com/prody/ProDy/files/8366601/merP2Functional.py.zip)
I accomplished what I wanted using Parmed, but I had to spend a lot of time on it to get it to work.  The topology and coordinates have to be separately subsetted and written.  Solution attached for anyone coming across this issue or your interest.

**Comment by jamesmkrieger** [comment] 2022-03-29 11:27
I now have a fix for this (#1517). The problem isn't that these properties were lost but rather that they were already missing and ProDy wasn't accounting for this properly.

**Closed** 2022-03-31 13:05 UTC

**Comment by jamesmkrieger** [comment] 2022-03-31 13:07
This is now merged so you should be able to use it
