### ISSUE TITLE
Biopython deprecation warning with ProDy plugin on VMD

### ISSUE THREAD

**Issue by cpayal** [prody/ProDy#1625] opened 2022-11-22 22:41 UTC
Hi 

I used to be able to successfully use the ProDy plugin on VMD, untill recently, when I started seeing the following error:

```
/home/pchatterjee/.conda/envs/prody/lib/python3.11/site-packages/Bio/pairwise2.py:278: BiopythonDeprecationWarning: Bio.pairwise2 has been deprecated, and we intend to remove it in a future release of Biopython. As an alternative, please consider using Bio.Align.PairwiseAligner as a replacement, and contact the Biopython developers if you still need the Bio.pairwise2 module.
  warnings.warn(
/home/pchatterjee/.conda/envs/prody/lib/python3.11/site-packages/Bio/pairwise2.py:278: BiopythonDeprecationWarning: Bio.pairwise2 has been deprecated, and we intend to remove it in a future release of Biopython. As an alternative, please consider using Bio.Align.PairwiseAligner as a replacement, and contact the Biopython developers if you still need the Bio.pairwise2 module.
  warnings.warn(
    while executing
"exec $::NMWiz::pybin $::NMWiz::prody anm --quiet -s $selstr {*}$args "$pdbfn""
    (procedure "::NMWiz::prodySubmitANMjob" line 42)
    invoked from within
"::NMWiz::prodySubmitANMjob"
    (procedure "::NMWiz::prodySubmitJob" line 22)
    invoked from within
"::NMWiz::prodySubmitJob"
    invoked from within
".nmwizprody.submitFrame.prodySubmit invoke"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 [list $w invoke]"
    (procedure "tk::ButtonUp" line 22)
    invoked from within
"tk::ButtonUp .nmwizprody.submitFrame.prodySubmit"
    (command bound to event)
```

The `BiopythonDeprecationWarning:` is key here. 

I am presently using the latest version of prody installed in a separate conda environment and calling VMD from there - to supress previous errors related to "imp" module which was also deprecated. 

Please let me know if I should rather contact the VMD forum.

Thanks
Payal

**Comment by jamesmkrieger** [comment] 2022-11-22 23:05
Hello, 

yes, I think the problem is that any warning or error written by the ProDy app is taken as an error by VMD, so now we get one from biopython and that breaks it even though it’s just a warning.

we’ll look into how our imports are done to see if we can avoid this. 

It’s also a good thing to know generally and account for in other ProDy functions. Thanks

**Comment by jamesmkrieger** [comment] 2023-01-17 17:57
I now have a fix for this. Once it passes the checks, I will merge it and then you can update your ProDy again and avoid this problem

**Comment by jamesmkrieger** [comment] 2023-01-17 18:17
ok, please update prody and try again

**Closed** 2023-01-31 15:40 UTC

**Comment by cpayal** [comment] 2023-03-30 18:51
Thanks for the earlier fix. It did work for a while. Sorry for not providing the feedback earlier but I see another warning which prevents VMD from performing the calculation :

`home/pchatterjee/.local/lib/python3.9/site-packages/Bio/pairwise2.py:278: BiopythonDeprecationWarning: Bio.pairwise2 has been deprecated, and we intend to remove it in a future release of Biopython. As an alternative, please consider using Bio.Align.PairwiseAligner as a replacement, and contact the Biopython developers if you still need the Bio.pairwise2 module.
  warnings.warn(
/home/pchatterjee/.local/lib/python3.9/site-packages/Bio/pairwise2.py:278: BiopythonDeprecationWarning: Bio.pairwise2 has been deprecated, and we intend to remove it in a future release of Biopython. As an alternative, please consider using Bio.Align.PairwiseAligner as a replacement, and contact the Biopython developers if you still need the Bio.pairwise2 module.`

**Comment by jamesmkrieger** [comment] 2023-03-30 19:01
I thought I fixed this in the latest prody too. Please can you try updating from github
