### ISSUE TITLE
Lost functionnality in new version of parsePDB? 

### ISSUE THREAD

**Issue by BarCollignon** [prody/ProDy#1708] opened 2023-06-14 07:22 UTC
I'm currently taking an old python 2.7 code and bringing it to 3.10. It uses Prody and a lot of it's functions. 
At some point, the code takes a pdb file and divides it along it's different segments. 
it looks like 
`REMARK selection chain A
ATOM 1 N .....
ATOM 2 H .....
...
...
END
REMARK selection chain B 
ATOM 1 C .... 
ATOM 2 H ....
....
....
END`

This worked in 2.7 with the old version of prody (1.7), but not in 2.4 
Is it normal? Is there a reason this no longer works in prody?

**Comment by jamesmkrieger** [comment] 2023-06-14 07:37
Hello, 

we try and maintain functionality so something shouldn’t have got broken. 

Can you share a code snippet for that part for us to check please?

That’s a big jump from prody 1.7 to 2.4 and Python 2.7 to 3.10 - can you try some intermediate things like prody 1.8 in Python 3.4?

Many thanks

**Comment by jamesmkrieger** [comment] 2023-06-14 07:40
Oh, also please try prody 2.4 in Python 2.7 as there should still be back compatibility 

you may also want to try Python 3.8 or 3.9

**Comment by jamesmkrieger** [comment] 2023-06-14 11:35
Also, why do you think the problem is with parsePDB?

**Comment by BarCollignon** [comment] 2023-06-14 11:55
Where can i download prody 1.8? i can find the release notes but i can't seem the find the link 

The line of code that bugs goes like 
`treated_pdb_file = pre-treatement(pdb_file)

atoms = parsePDB(treated_pdb_file) 

post-treatement(atoms)
`

and the line with parsePDB bugs. If i put 

`atoms = parsePDB(pdb_file)`

that runs without problems (just crashes later down the line because it didn't go through pre-treatement).

**Comment by jamesmkrieger** [comment] 2023-06-14 12:05
> (nevermind about version 1.8, found it)

Good

**Comment by BarCollignon** [comment] 2023-06-14 12:06
running the same code with 
pip install ProDy==1.8 before gives me :

**Comment by jamesmkrieger** [comment] 2023-06-14 12:08
> Where can i download prody 1.8? i can find the release notes but i can't seem the find the link
> 
> The line of code that bugs goes like `treated_pdb_file = pre-treatement(pdb_file)
> 
> atoms = parsePDB(treated_pdb_file)
> 
> post-treatement(atoms) `
> 
> and the line with parsePDB bugs. If i put
> 
> `atoms = parsePDB(pdb_file)`
> 
> that runs without problems (just crashes later down the line because it didn't go through pre-treatement).

Ok, I see. So the problem is with parsing pdb files with REMARK lines in between ATOM lines? I think there’s a similar problem in #1687

I’m not sure why that would have become a problem between versions but it should be possible to track down

**Comment by jamesmkrieger** [comment] 2023-06-14 12:11
> running the same code with pip install ProDy==1.8 before gives me :
> 
> from prody import * File "/home/local/miniconda3/lib/python3.10/site-packages/prody/**init**.py", line 68, in from . import atomic File "/home/local/miniconda3/lib/python3.10/site-packages/prody/atomic/**init**.py", line 154, in from .select import * File "/home/local/miniconda3/lib/python3.10/site-packages/prody/atomic/select.py", line 451, in from . import pyparsing as pp File "/home/local/miniconda3/lib/python3.10/site-packages/prody/atomic/pyparsing.py", line 615, in collections.MutableMapping.register(ParseResults) AttributeError: module 'collections' has no attribute 'MutableMapping'

Is this the same problem as in 2.4? Perhaps it’s something about python 3.10

Have you tried python 3.7 or 3.8?

**Comment by BarCollignon** [comment] 2023-06-14 12:15
in 2.4 this is the error i'm getting : 
file.pdb  (<class 'IndexError'>, IndexError('list index out of range'), <traceback object at 0x7fb6160a5300>)

i'll try in 3.8 as soon as i can

Thank you for taking the time to help me

**Comment by jamesmkrieger** [comment] 2023-06-14 12:56
ok, odd

you're welcome

I think the problem in 1.8 is specific to that version actually as there isn't a prody/atomic/pyparsing.py in later versions. Perhaps you could try 1.9

**Comment by BarCollignon** [comment] 2023-06-14 12:59
sorry about 3.7, takes some time i have to recreate a new environnement... 

prody 1.9 with python 3.10 : 
  from prody import *
  File "/home/local/miniconda3/lib/python3.10/site-packages/prody/__init__.py", line 68, in <module>
  from . import atomic
  File "/home/local/miniconda3/lib/python3.10/site-packages/prody/atomic/__init__.py", line 154, in <module>
  from .select import *
  File "/home/local/miniconda3/lib/python3.10/site-packages/prody/atomic/select.py", line 444, in <module>
  from collections import Iterable
ImportError: cannot import name 'Iterable' from 'collections' (/home/local/miniconda3/lib/python3.10/collections/__init__.py)

**Comment by jamesmkrieger** [comment] 2023-06-14 13:05
ok. That was fixed in 2.0.2 so you can probably only check back to there with python 3.10

Yes, I know it takes time for making new environments. Sorry about that

**Comment by BarCollignon** [comment] 2023-06-14 13:16
In 2.0.2 it passed!

**Comment by jamesmkrieger** [comment] 2023-06-14 13:48
ok. Thanks. That should make it quite a bit easier to track down.

**Comment by jamesmkrieger** [comment] 2023-10-12 12:02
Even in ProDy 1.7 in Python 2.7, parsePDB only parses chain A from a file like you describe with END and REMARK lines in between chains (based on pdb 2nwl):

```
REMARK Selection 'chain A'
ATOM      1  N   TYR A  10     -25.955  27.759 -13.751  1.00199.26         A N  
ATOM      2  CA  TYR A  10     -25.035  28.564 -12.891  1.00199.14         A C  
.
.
.
ATOM   2885  OE1 GLU A 416      16.853  25.876 -17.344  1.00154.67         A O  
ATOM   2886  OE2 GLU A 416      17.573  24.630 -18.998  1.00161.05         A O  
REMARK selection 'chain B'
ATOM   2887  N   TYR B  10     -10.893 -36.331 -13.647  1.00179.36         B N  
ATOM   2888  CA  TYR B  10     -12.102 -35.917 -12.871  1.00180.45         B C  
.
.
.
ATOM   5748  OE1 GLU B 416     -30.734   1.305 -17.838  1.00155.80         B O  
ATOM   5749  OE2 GLU B 416     -30.249   2.537 -19.593  1.00155.00         B O  
END
```

```
Python 2.7.18 |Anaconda, Inc.| (default, Nov 25 2022, 06:27:37) 
[GCC 11.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from prody import *
>>> ag = parsePDB('ProDy/prody/tests/datafiles/pdb2nwl-protein.pdb')
@> 2886 atoms and 1 coordinate set(s) were parsed in 0.01s.
>>> list(ag.protein.getHierView())
[<Chain: A from Segment A from pdb2nwl-protein (402 residues, 2886 atoms)>]
>>> prody.__version__
'1.7'
```

If you only have REMARK lines as in the file below based on 2nwl, both ProDy 1.7 in Python 2.7 and latest ProDy development version 2.4.1 in Python 3.8 can read through both chains fine:

```
REMARK Selection 'chain A'
ATOM      1  N   TYR A  10     -25.955  27.759 -13.751  1.00199.26         A N  
ATOM      2  CA  TYR A  10     -25.035  28.564 -12.891  1.00199.14         A C  
.
.
.
ATOM   2885  OE1 GLU A 416      16.853  25.876 -17.344  1.00154.67         A O  
ATOM   2886  OE2 GLU A 416      17.573  24.630 -18.998  1.00161.05         A O  
REMARK selection 'chain B'
ATOM   2887  N   TYR B  10     -10.893 -36.331 -13.647  1.00179.36         B N  
ATOM   2888  CA  TYR B  10     -12.102 -35.917 -12.871  1.00180.45         B C  
.
.
.
ATOM   5748  OE1 GLU B 416     -30.734   1.305 -17.838  1.00155.80         B O  
ATOM   5749  OE2 GLU B 416     -30.249   2.537 -19.593  1.00155.00         B O  
END
```

```
Python 2.7.18 |Anaconda, Inc.| (default, Nov 25 2022, 06:27:37) 
[GCC 11.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from prody import *
>>> ag = parsePDB('ProDy/prody/tests/datafiles/pdb2nwl-protein.pdb')
@> 5749 atoms and 1 coordinate set(s) were parsed in 0.02s.
>>> list(ag.protein.getHierView())
[<Chain: A from Segment A from pdb2nwl-protein (402 residues, 2886 atoms)>, <Chain: B from Segment B from pdb2nwl-protein (398 residues, 2863 atoms)>]
>>> prody.__version__
'1.7'
```

```
Python 3.8.13 (default, Mar 28 2022, 11:38:47) 
Type 'copyright', 'credits' or 'license' for more information
IPython 8.3.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from prody import *

In [2]: ag = parsePDB('ProDy/prody/tests/datafiles/pdb2nwl-protein.pdb')
@> 5749 atoms and 1 coordinate set(s) were parsed in 0.05s.

In [3]: list(ag.protein.getHierView())
Out[3]: 
[<Chain: A from Segment A from pdb2nwl-protein (402 residues, 2886 atoms)>,
 <Chain: B from Segment B from pdb2nwl-protein (398 residues, 2863 atoms)>]

In [4]: prody.__version__
Out[4]: '2.4.1'
```

So, I'd suggest you change how you make the files.

It won't be able to make any use of the REMARK information, but hopefully that's ok.

**Comment by jamesmkrieger** [comment] 2023-11-05 18:29
I'm assuming this resolves your issue and I'm closing it, but please feel free to reopen it.

**Closed by jamesmkrieger** 2023-11-05 18:29 UTC
